# Generated by Django 2.0.7 on 2018-08-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confirmstring',
            name='user',
            field=models.OneToOneField(on_delete=False, to='bbsapp.UserInfo'),
        ),
    ]
